import sqlite3

DATABASE_PATH = 'instance/database.db'

def create_profile(name, user_id=None):
    """
    Creates a profile with the provided name and user_id if they don't already exist.
    
    Parameters:
    - name: str - The name associated with the profile
    - user_id: str - The unique user ID (optional, autogenerated if not provided)
    
    Returns:
    - A dictionary indicating success or failure
    """
    if not name:
        return {"success": False, "error": "Name is required."}, 400

    try:
        with sqlite3.connect(DATABASE_PATH) as conn:
            cursor = conn.cursor()
            cursor.execute("INSERT INTO profiles (user_id, name) VALUES (?, ?)", (user_id, name))
            conn.commit()
            return {"success": True, "message": "Profile created successfully.", "Name": name}
    except sqlite3.IntegrityError:
        return {"success": False, "error": "Profile with this name or user_id already exists."}, 409
    except Exception as e:
        return {"success": False, "error": str(e)}, 500